### PR TITLE
Issue 33: Usage With Elements Within Shadow Dom

### PR DESCRIPTION
**Pull request by israelfloresdga**
Fix issue [#33](https://github.com/yiminghe/dom-align/issues/33)

### CODE REVIEW

**Comment by israelfloresdga** [comment]
Mmm, I'm new, how I update the pull request?

**Comment by Mechrophile** [comment]
Hey, just chiming in here to say this change would be extremely valuable to me!  
@yiminghe fingers crossed to get this in!

**Comment by yiminghe** [comment]
need a testcase

**Comment by yiminghe** [comment]
https://github.com/yiminghe/dom-align/commit/562fcec15201b84794510dcb2be62fdadf3325e5

**Pull request closed without merging**
